//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLayer.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHistoriatet
    {
        public int HistoriatiID { get; set; }
        public System.DateTime HistoriatiData { get; set; }
        public int HistoriatiLlojiID { get; set; }
        public int PerdoruesiID { get; set; }
        public string IP { get; set; }
        public string Tabela { get; set; }
        public string TabelaCelesi { get; set; }
        public string ObjektiThirres { get; set; }
        public string Transaksioni { get; set; }
    
        public virtual tblHistoriatetLlojet tblHistoriatetLlojet { get; set; }
    }
}
