//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLayer.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHuazimi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblHuazimi()
        {
            this.tblKthimi = new HashSet<tblKthimi>();
        }
    
        public int HuazimiID { get; set; }
        public Nullable<int> PerdoruesiID { get; set; }
        public Nullable<int> LibriID { get; set; }
        public Nullable<int> Sasia { get; set; }
        public Nullable<System.DateTime> DataHuazimit { get; set; }
        public Nullable<System.DateTime> DataKthimit { get; set; }
        public string Shenime { get; set; }
        public Nullable<int> PerdoruesiIDLexuesi { get; set; }
    
        public virtual tblLibri tblLibri { get; set; }
        public virtual tblPerdoruesit tblPerdoruesit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKthimi> tblKthimi { get; set; }
    }
}
