//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLayer.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKthimi
    {
        public int KthimiID { get; set; }
        public Nullable<int> LibriID { get; set; }
        public Nullable<int> PerdoruesiID { get; set; }
        public Nullable<int> Sasia { get; set; }
        public Nullable<System.DateTime> DataKthimit { get; set; }
        public Nullable<bool> Domtuar { get; set; }
        public Nullable<decimal> Pages { get; set; }
        public Nullable<int> SasiaDomtuar { get; set; }
        public Nullable<int> HuazimiID { get; set; }
    
        public virtual tblHuazimi tblHuazimi { get; set; }
        public virtual tblLibri tblLibri { get; set; }
        public virtual tblPerdoruesit tblPerdoruesit { get; set; }
    }
}
