//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLayer.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLibri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLibri()
        {
            this.tblHuazimi = new HashSet<tblHuazimi>();
            this.tblKthimi = new HashSet<tblKthimi>();
        }
    
        public int LibriID { get; set; }
        public string ISBN { get; set; }
        public string TittulliLibrit { get; set; }
        public int Sasia { get; set; }
        public int AutoriID { get; set; }
        public int GjuhaLibritID { get; set; }
        public string Botimi { get; set; }
        public Nullable<int> VitiBotimit { get; set; }
        public Nullable<int> NumriFaqeve { get; set; }
        public Nullable<int> ShtepiaBotuseID { get; set; }
        public Nullable<int> DhomaID { get; set; }
        public Nullable<int> RaftiID { get; set; }
        public string DonacionPershkrimi { get; set; }
        public Nullable<System.DateTime> DataInsertimi { get; set; }
        public Nullable<int> PerdoruesiID { get; set; }
    
        public virtual tblAutori tblAutori { get; set; }
        public virtual tblDhoma tblDhoma { get; set; }
        public virtual tblGjuhaLibrit tblGjuhaLibrit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHuazimi> tblHuazimi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKthimi> tblKthimi { get; set; }
        public virtual tblPerdoruesit tblPerdoruesit { get; set; }
        public virtual tblRafti tblRafti { get; set; }
    }
}
