//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLayer.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLibri
    {
        public int LibriID { get; set; }
        public string ISBN { get; set; }
        public string TittulliLibrit { get; set; }
        public int Sasia { get; set; }
        public int AutoriID { get; set; }
        public int GjuhaLibritID { get; set; }
        public string Botimi { get; set; }
        public Nullable<int> VitiBotimit { get; set; }
        public Nullable<int> NumriFaqeve { get; set; }
        public Nullable<int> ShtepiaBotuseID { get; set; }
        public Nullable<int> DhomaID { get; set; }
        public Nullable<int> RaftiID { get; set; }
        public string DonacionPershkrimi { get; set; }
        public Nullable<System.DateTime> DataInsertimi { get; set; }
    }
}
