//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLayer.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPerdoruesit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPerdoruesit()
        {
            this.tblHuazimi = new HashSet<tblHuazimi>();
            this.tblKthimi = new HashSet<tblKthimi>();
            this.tblLibri = new HashSet<tblLibri>();
        }
    
        public int PerdoruesiID { get; set; }
        public string NumriPersonal { get; set; }
        public string Emri { get; set; }
        public string Mbiemri { get; set; }
        public string Perdoruesi { get; set; }
        public byte[] Fjalkalimi { get; set; }
        public int KomunaID { get; set; }
        public string Adresa { get; set; }
        public string Email { get; set; }
        public string Telefoni { get; set; }
        public Nullable<System.DateTime> DateLindja { get; set; }
        public int GrupiID { get; set; }
        public System.DateTime DataInsertimit { get; set; }
    
        public virtual tblGrupi tblGrupi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHuazimi> tblHuazimi { get; set; }
        public virtual tblKomunat tblKomunat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKthimi> tblKthimi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLibri> tblLibri { get; set; }
    }
}
