//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLayer.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPerdoruesit
    {
        public int PerdoruesiID { get; set; }
        public string NumriPersonal { get; set; }
        public string Emri { get; set; }
        public string Mbiemri { get; set; }
        public int KomunaID { get; set; }
        public string Adresa { get; set; }
        public string Email { get; set; }
        public string Telefoni { get; set; }
        public Nullable<System.DateTime> DateLindja { get; set; }
        public int GrupiID { get; set; }
        public System.DateTime DataInsertimit { get; set; }
        public byte[] Fjalkalimi { get; set; }
    }
}
